// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAmRr9CH4eY3Jw3AJOhpcDbibLS4GtYC0',
    appId: '1:940439866279:web:c82adb126a448fb5070482',
    messagingSenderId: '940439866279',
    projectId: 'brackets-7db43',
    authDomain: 'brackets-7db43.firebaseapp.com',
    storageBucket: 'brackets-7db43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6PLNSf92X9OHYpnxHk-lHGU7b2RypWU0',
    appId: '1:940439866279:android:9a3599b5be526e9c070482',
    messagingSenderId: '940439866279',
    projectId: 'brackets-7db43',
    storageBucket: 'brackets-7db43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjvRMF09vDvYQxk0l1UpB-4CI6vsro5Os',
    appId: '1:940439866279:ios:149feb6ebdde9142070482',
    messagingSenderId: '940439866279',
    projectId: 'brackets-7db43',
    storageBucket: 'brackets-7db43.appspot.com',
    iosClientId: '940439866279-6fl2rks7ekp9t0ue0umns6e4lpcr4gce.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieBracket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjvRMF09vDvYQxk0l1UpB-4CI6vsro5Os',
    appId: '1:940439866279:ios:4bf2dabc0b126bc2070482',
    messagingSenderId: '940439866279',
    projectId: 'brackets-7db43',
    storageBucket: 'brackets-7db43.appspot.com',
    iosClientId: '940439866279-3u1tfdh70q70nt8ctde6vi4v49kvsg5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieBracket.RunnerTests',
  );
}
